Splash screen
SavBetuel/HungryWolfs pull request #1
Opened 2021-08-10 07:47 UTC by SavBetuel

2021-08-10 07:51 UTC, vasileGrad commented on app/src/main/java/com/example/hungrywolfs/MainActivity.kt
> +        //sleep(1000)
You can remove this comment

2021-08-10 08:02 UTC, vasileGrad submitted a review, later dismissed

2021-08-10 09:53 UTC, cristiwd requested changes

2021-08-10 09:53 UTC, cristiwd commented on app/src/main/AndroidManifest.xml
> +        android:theme="@style/splashScreenTheme">
Hmm. 
The app theme should be set on the the application, and the 'splashScreenTheme' should be set only on that specific activity. Also take care of the naming, usually styles start with uppercase.

2021-08-10 09:53 UTC, cristiwd commented on app/src/main/java/com/example/hungrywolfs/MainActivity.kt
> +        setTheme(R.style.Theme_HungryWolfs)
Not needed if the theme is set back on the application tag in manifest. Or could be set there on the activity tag.

2021-08-11 04:42 UTC, MGabi requested changes

2021-08-11 04:42 UTC, MGabi commented on app/src/main/res/layout/activity_splash_screen.xml
> +        android:text="Hungry\nWolfs"
Make sure every text is extracted to strings.xml, not hardcoded in XML

2021-08-11 14:08 UTC, cristiwd requested changes

2021-08-11 14:08 UTC, cristiwd commented on app/src/main/res/layout/activity_splash_screen.xml
> +        android:textSize="65dp"
For text sizes we should use Scale-independent Pixels (**sp**). 
https://developer.android.com/guide/topics/resources/more-resources#Dimension
And also extract it to dimes.xml.

2021-08-11 14:08 UTC, cristiwd commented on app/src/main/res/layout/activity_splash_screen.xml
> +        android:layout_marginStart="32dp"
Please extract these margins to dimes.xml.

2021-08-12 05:53 UTC, MGabi approved these changes

2021-08-12 06:55 UTC, cristiwd approved these changes

2021-08-12 14:27 UTC, merged