Feature/home screen
SavBetuel/HungryWolfs pull request #2
Opened 2021-08-14 12:16 UTC by SavBetuel

2021-08-17 06:19 UTC, cristiwd requested changes

2021-08-17 06:19 UTC, cristiwd commented on app/src/main/java/com/example/hungrywolfs/network/FoodApiService.kt
> +    suspend fun getFoodHomeFragment(@Query("c") filter: String?): FoodHomeFragment
Suggestion. Better naming: getFoodItems? getCategoryFoodItems? This shouldn't care or know where the data is used. It could also be used on multiple screens.

2021-08-17 06:19 UTC, cristiwd commented on app/src/main/java/com/example/hungrywolfs/model/OverviewViewModel.kt
> +    private val _foodHomeFragment = MutableLiveData<FoodHomeFragment>()
A better naming here would be great. foodItems maybe? Shouldn't be linked to some Fragment.

2021-08-17 06:19 UTC, cristiwd commented on app/src/main/java/com/example/hungrywolfs/fragments/HomeFragment.kt
> +        divider(requireContext(), binding.categoriesRecyclerView)
divider?
Better naming again. 
"In short, nouns are properties and **verbs** are **methods**."
Suggestion: change the name to setupRecyclerView and include setting the adapter inside the method. You'll need to pass the adapter as parameter as well.

2021-08-17 06:19 UTC, cristiwd commented on app/src/main/res/layout/food_view_item.xml
> +    <LinearLayout
This layout is not needed.
Also, we discussed to add the text view inside the CardView.

2021-08-17 06:29 UTC, cristiwd requested changes

2021-08-17 06:29 UTC, cristiwd commented on app/src/main/java/com/example/hungrywolfs/adapters/CategoriesAdapter.kt
> +            notifyItemChanged(position, position)
Why using the second parameter? That should be the payload, not the position.

2021-08-17 06:51 UTC, MGabi requested changes

2021-08-17 06:51 UTC, MGabi commented on app/src/main/java/com/example/hungrywolfs/fragments/HomeFragment.kt
> +        divider(requireContext(), binding.categoriesRecyclerView)
One more thing here - you dont need to pass context via a variable because it's accessible directly in that method too

2021-08-17 06:51 UTC, MGabi commented on app/src/main/res/layout/fragment_favourites.xml
> +<FrameLayout xmlns:android="http://schemas.android.com/apk/res/android"
Why do we wrap the layout here in a FrameLayout?
Is it really needed?

2021-08-17 06:51 UTC, MGabi commented on app/src/main/res/layout/fragment_profile.xml
> +<FrameLayout xmlns:android="http://schemas.android.com/apk/res/android"
Same question as above

2021-08-17 07:44 UTC, cristiwd commented on app/src/main/java/com/example/hungrywolfs/fragments/HomeFragment.kt
> +    private val viewModel: OverviewViewModel by activityViewModels()
activityViewModels() is usually used to get the viewModel instance from the parent activity in order to communicate with other fragments. 
https://developer.android.com/topic/libraries/architecture/viewmodel#sharing

Here you could use **by viewModels()**.

2021-08-17 08:24 UTC, mihai-wolfpack commented on app/src/main/java/com/example/hungrywolfs/adapters/HomeFoodAdapter.kt
> +    private val data: MutableList<FoodSelected> = mutableListOf()
you do not have to also mention the type, you could just write 
`private val data = mutableListOf<FoodSelected>()`

2021-08-17 08:26 UTC, mihai-wolfpack commented on app/src/main/java/com/example/hungrywolfs/model/OverviewViewModel.kt
> +                Log.d("DEB_category", "Error at getting the category from API")
Usually, `Log.d` is for "debug", whenever we are catching errors and we want to log them, it is indicated we use`Log.e`

2021-08-17 08:44 UTC, cristiwd approved these changes

2021-08-18 05:27 UTC, MGabi approved these changes

2021-08-18 06:06 UTC, merged