Feature/search screen
SavBetuel/HungryWolfs pull request #3
Opened 2021-08-18 10:12 UTC by SavBetuel

2021-08-18 14:51 UTC, cristiwd requested changes

2021-08-18 14:51 UTC, cristiwd commented on app/src/main/res/layout/food_search_item.xml
> +        android:layout_width="130dp"
Don't forget to extract resources.

2021-08-18 14:51 UTC, cristiwd commented on app/src/main/java/com/example/hungrywolfs/fragments/SearchFragment.kt
> +    private val viewModel: SearchViewModel by activityViewModels()
activityViewModels() vs viewModels()

2021-08-18 14:51 UTC, cristiwd commented on app/src/main/java/com/example/hungrywolfs/fragments/SearchFragment.kt
> +        viewModel.getSearchFood("Be")
Is this search needed?

2021-08-18 14:51 UTC, cristiwd commented on app/src/main/java/com/example/hungrywolfs/fragments/SearchFragment.kt
> +    var foundResults: Int = 0
Is it used anymore?

2021-08-18 14:51 UTC, cristiwd commented on app/src/main/java/com/example/hungrywolfs/fragments/SearchFragment.kt
> +            foundResults = viewModel.foodSearch.value!!.meals.size
[The !! operator﻿](https://kotlinlang.org/docs/null-safety.html#the-operator) is generally not recommended since it could hide a possible NPE. You could use an [Elvis operator](https://kotlinlang.org/docs/null-safety.html#elvis-operator) at the end of the line and set a default value of 0 ( ?: 0).
Most probably you don't need the foundResults variable anymore, but please read the documentation at these links.

2021-08-18 17:48 UTC, SavBetuel commented on app/src/main/java/com/example/hungrywolfs/fragments/SearchFragment.kt
> +        viewModel.getSearchFood("Be")
Apparently not:) I thought it was necessary to use it to display data when entering the search fragment, before writing/searching anything. I didn't notice that I still get data from API even if the query filter is null.

2021-08-18 17:51 UTC, SavBetuel commented on app/src/main/java/com/example/hungrywolfs/fragments/SearchFragment.kt
> +    var foundResults: Int = 0
No, I tested something and forgot to delete it afterwards

2021-08-19 05:38 UTC, cristiwd approved these changes

2021-08-19 06:47 UTC, merged